<a href="https://colab.research.google.com/github/vikranthrach/IIT-Patna--AI-and-ML-Course/blob/main/Masai_Assignment_Problems_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem Statement:**

A data analyst needs to analyze customer order data from an e-commerce database. You are given a database with two tables: customers (columns: customer_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, city TEXT) and orders (columns: order_id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER FOREIGN KEY, amount REAL, order_date DATE). Write a complete Python script that:

Creates both tables (if they do not exist)

Inserts sample customer and order data

Executes a query to retrieve customers from New York who placed orders over 100 dollars, displaying customer name, city, and order amount

Saves the query results to a Pandas DataFrame

Outputs the results

The script should demonstrate proper database connection handling, table creation with constraints, batch inserts, and query execution.

Constraints & Requirements:

Use SQLite3 with a file-based database named ecommerce.db
Use executemany() for batch inserts
Include NOT NULL and UNIQUE constraints where appropriate
Write a single SQL query that combines filtering conditions (WHERE, AND)
Close the database connection after operations complete
Include comments explaining non-obvious steps
Example Input / Expected Output:

Input: **bold text** Sample data with 3 customers and 4 orders; at least one customer from New York with an order over $100
Expected Output: A DataFrame (and printed output) showing the customer name, city, and order amount for qualifying records

In [ ]:
# Import required libraries

import sqlite3

import pandas as pd



# ---------------------------------------------------

# STEP 1: Create/connect to database

# ---------------------------------------------------



# This creates a database file named ecommeerce.db

connection = sqlite3.connect("ecommerce.db")



# Cursor is used to execute SQL commands

cursor = connection.cursor()



print("Database connected successfully!")



# ---------------------------------------------------

# STEP 2: Create tables with constraints

# ---------------------------------------------------



# Create Customers table

cursor.execute("""

CREATE TABLE IF NOT EXISTS customers (

    customer_id INTEGER PRIMARY KEY,

    name TEXT NOT NULL,

    city TEXT NOT NULL

)

""")



# Create Orders table

cursor.execute("""

CREATE TABLE IF NOT EXISTS orders (

    order_id INTEGER PRIMARY KEY,

    customer_id INTEGER,

    product TEXT NOT NULL,

    amount REAL CHECK(amount > 0),



    FOREIGN KEY(customer_id)

    REFERENCES customers(customer_id)

)

""")



print("Tables created successfully!")



# ---------------------------------------------------

# STEP 3: Insert sample data using executemany()

# ---------------------------------------------------



# Sample customer data

customers_data = [

    (1, "Alice", "New York"),

    (2, "Bob", "Chicago"),

    (3, "Charlie", "New York"),

    (4, "David", "Boston")

]



# Insert customers

cursor.executemany("""

INSERT OR REPLACE INTO customers

(customer_id, name, city)

VALUES  (?, ?, ?)""", customers_data)



# Sample orders data

orders_data = [

    (101, 1, "Laptop", 1200),

    (102, 2, "Mouse", 25),

    (103, 3, "Keyboard", 150),

    (104, 1, "Monitor", 300),

    (105, 4, "USB Cable", 15)

]



# Insert orders

cursor.executemany("""

INSERT OR REPLACE INTO orders

(order_id, customer_id, product, amount)

VALUES (?, ?, ?, ?)

""", orders_data)



# Save changes

connection.commit()



print("Sample data inserted successfully!")



# ---------------------------------------------------

# STEP 4: Query customers from New York

#         with orders over 100

# ---------------------------------------------------



query = """

SELECT

    customers.customer_id,

    customers.name,

    customers.city,

    orders.product,

    orders.amount

FROM customers

JOIN orders

ON customers.customer_id = orders.customer_id

WHERE customers.city = 'New York'

AND orders.amount > 100

"""



# ---------------------------------------------------

# STEP 5: Load results into Pandas DataFrame

# ---------------------------------------------------



df = pd.read_sql_query(query, connection)



print("\nQuery Results:")

print(df)



# ---------------------------------------------------

# STEP 6: Close the connection

# ---------------------------------------------------



cursor.close()

connection.close()



print("\nDatabase connection closed!")

**Pandas Problem:**
You are working with the Titanic dataset, which has 891 rows and columns including sex, pclass, age, fare, embarked, and survived. The dataset has 177 missing values in the age column (approximately 20% of records).

Your task is to write a complete Python script using Pandas that performs the following data analysis pipeline:

Requirements:

Load the Titanic dataset from a CSV file called titanic.csv using read_csv
Filter passengers who are female AND in pclass 1 or pclass 2 (use isin for the pclass check)
From this filtered group, fill missing age values with the value 30 using fillna
Sort the filtered DataFrame by fare in descending order, then reset the index so the index values are sequential from 0
Add a new column called fare_group that assigns the string 'high' to all rows (you may assign a constant string value to the new column)
Save the final result to a new CSV file called female_upper_class.csv

In [8]:

#Import Pandas

import pandas as pd

#---------------------------------------------
# STEP 1: Load Titanic dataset from CSV file
#---------------------------------------------

titanic=pd.read_csv("titanic.csv")

titanic
#---------------------------------------------------
# STEP 2:Filter Passengers
# Female passengers
# pclass is either 1 or 2
#---------------------------------------------------
passengers=titanic[(titanic["Sex"]=="female") & (titanic["Pclass"].isin([1,2]))]
passengers
#-----------------------------------
# STEP 3: Filling missing age values with 30
#--------------------------------------------

passengers=passengers.fillna(30)
passengers

#-------------------------------------------------------
# STEP 4: Sort by Fare in descending order
# Then reset index
#---------------------------------------------------------
passengers=passengers.sort_values(by="Fare",ascending=False).reset_index(drop=True)
passengers
#-------------------------------------------------------
# STEP 5: Add new column fare_group
#---------------------------------------------------------

passengers["fare_group"]="high"

#-------------------------------------------------------
# STEP 6: Save final result to new CSV file
#---------------------------------------------------------

passengers.to_csv("female_upper_class.csv",index=False)
passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [9]:
#---------------------------------------------------
# STEP 2:Filter Passengers
# Female passengers
# pclass is either 1 or 2
#---------------------------------------------------
passengers=titanic[(titanic["Sex"]=="female") & (titanic["Pclass"].isin([1,2]))]
passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [11]:
#-----------------------------------
# STEP 3: Filling missing age values with 30
#--------------------------------------------

passengers=passengers.fillna(30)
passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,30,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,30,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,30,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,30,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [15]:

#-------------------------------------------------------
# STEP 4: Sort by Fare in descending order
# Then reset index
#---------------------------------------------------------
passengers=passengers.sort_values(by="Fare",ascending=False).reset_index(drop=True)
passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,30,C
1,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
2,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
3,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
4,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...,...
165,459,1,2,"Toomey, Miss. Ellen",female,50.0,0,0,F.C.C. 13531,10.5000,30,S
166,527,1,2,"Ridsdale, Miss. Lucy",female,50.0,0,0,W./C. 14258,10.5000,30,S
167,517,1,2,"Lemore, Mrs. (Amelia Milley)",female,34.0,0,0,C.A. 34260,10.5000,F33,S
168,718,1,2,"Troutt, Miss. Edwina Celia ""Winnie""",female,27.0,0,0,34218,10.5000,E101,S
169,773,0,2,"Mack, Mrs. (Mary)",female,57.0,0,0,S.O./P.P. 3,10.5000,E77,S

In [16]:
#-------------------------------------------------------
# STEP 5: Add new column fare_group
#---------------------------------------------------------

passengers["fare_group"]="high"

In [18]:
#-------------------------------------------------------
# STEP 6: Save final result to new CSV file
#---------------------------------------------------------

passengers.to_csv("female_upper_class.csv",index=False)
passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_group
0,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,30,C,high
1,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,high
2,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S,high
3,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,high
4,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,459,1,2,"Toomey, Miss. Ellen",female,50.0,0,0,F.C.C. 13531,10.5000,30,S,high
166,527,1,2,"Ridsdale, Miss. Lucy",female,50.0,0,0,W./C. 14258,10.5000,30,S,high
167,517,1,2,"Lemore, Mrs. (Amelia Milley)",female,34.0,0,0,C.A. 34260,10.5000,F33,S,high
168,718,1,2,"Troutt, Miss. Edwina Celia ""Winnie""",female,27.0,0,0,34218,10.5000,E101,S,high
169,773,0,2,"Mack, Mrs. (Mary)",female,57.0,0,0,S.O./P.P. 3,10.5000,E77,S,high

**Problem** **statement**:You have been given a raw CSV file students.csv with the following content:

name,age,score,grade
Alice,22,88.5,A
Bob,20,73.0,B
Charlie,21,91.0,A
Diana,23,65.5,C
A data analyst needs to load this file, inspect it, and produce a cleaned summary. Specifically, you are asked to:

Load the CSV into a Pandas DataFrame.
Display the shape, column names, and data types of each column.
Run df.describe(), identify which columns are included in the output, and explain why certain columns are excluded.
Rename the column score to final_score and grade to letter_grade without modifying the original DataFrame (save the result to a new variable).
From the renamed DataFrame, select only the name, final_score, and letter_grade columns and display the result.
Using iloc, access the first 3 rows and all columns. Then using loc, access rows with index labels 1 and 3, and only the name and grade columns.

Walkthrough:

pd.read_csv('students.csv') loads the file and auto-assigns a default integer index starting at 0.
df.shape returns (4, 4) — 4 rows and 4 columns.
df.dtypes shows that name and grade are object (string) type, age is int64, and score is float64.
df.describe() only shows age and score because it only operates on numerical data. The two object columns (name, grade) are excluded.
df.rename(columns={...}) without inplace=True returns a new DataFrame. The original df is unchanged.
df_renamed[['name', 'final_score', 'letter_grade']] uses a list inside double brackets to select multiple columns, returning a DataFrame.
df.iloc[0:3] accesses rows at integer positions 0, 1, 2. Position 3 is exclusive.
df.loc[[1, 3], ['name', 'grade']] accesses rows by their actual index labels 1 and 3. Since the default index is 0–3, these correspond to Bob and Diana respectively.

In [22]:
import pandas as pd
 #(Answer provided in Assignment)

# Step 1: Load the CSV
df = pd.read_csv('students.csv')

# Step 2: Inspect structure
print(df.shape)        # (4, 4)
print(df.columns)      # Index(['name', 'age', 'score', 'grade'], dtype='object')
print(df.dtypes)
# name     object
# age       int64
# score   float64
# grade    object

# Step 3: Describe
print(df.describe())
# Only age and score appear — these are numerical (int64 and float64).
# 'name' and 'grade' are object (string) columns and are excluded from df.describe().

# Step 4: Rename without modifying original
df_renamed = df.rename(columns={'score': 'final_score', 'grade': 'letter_grade'})
# df still has original column names; df_renamed has the new names

# Step 5: Select specific columns from renamed DataFrame
result = df_renamed[['name', 'final_score', 'letter_grade']]
print(result)

# Step 6a: iloc — first 3 rows, all columns
print(df.iloc[0:3])   # Rows at positions 0, 1, 2 — position 3 is excluded (iloc is exclusive at end)

# Step 6b: loc — rows with labels 1 and 3 and specific columns
print(df.loc[[1, 3], ['name', 'grade']])
# loc uses actual index labels (0-3 after read_csv) and is inclusive

(4, 4)
Index(['name', 'age', 'score', 'grade'], dtype='object')
name      object
age        int64
score    float64
grade     object
dtype: object
             age      score
count   4.000000   4.000000
mean   21.500000  79.500000
std     1.290994  12.267844
min    20.000000  65.500000
25%    20.750000  71.125000
50%    21.500000  80.750000
75%    22.250000  89.125000
max    23.000000  91.000000
      name  final_score letter_grade
0    Alice         88.5            A
1      Bob         73.0            B
2  Charlie         91.0            A
3    Diana         65.5            C
      name  age  score grade
0    Alice   22   88.5     A
1      Bob   20   73.0     B
2  Charlie   21   91.0     A
    name grade
1    Bob     B
3  Diana     C

'" Walkthrough:\n\npd.read_csv(\'students.csv\') loads the file and auto-assigns a default integer index starting at 0.\ndf.shape returns (4, 4) — 4 rows and 4 columns.\ndf.dtypes shows that name and grade are object (string) type, age is int64, and score is float64.\ndf.describe() only shows age and score because it only operates on numerical data. The two object columns (name, grade) are excluded.\ndf.rename(columns={...}) without inplace=True returns a new DataFrame. The original df is unchanged.\ndf_renamed[[\'name\', \'final_score\', \'letter_grade\']] uses a list inside double brackets to select multiple columns, returning a DataFrame.\ndf.iloc[0:3] accesses rows at integer positions 0, 1, 2. Position 3 is exclusive.\ndf.loc[[1, 3], [\'name\', \'grade\']] accesses rows by their actual index labels 1 and 3. Since the default index is 0–3, these correspond to Bob and Diana respectively.'

In [ ]:
import pandas as pd

#---------------------------------------------
# STEP 1: Load students dataset from CSV file
#---------------------------------------------

students=pd.read_csv("students.csv")

students

In [6]:
import pandas as pd

#---------------------------------------------
# STEP 1: Load students dataset from CSV file
#---------------------------------------------

students=pd.read_csv("students.csv")

#-----------------------------------------------------------------------
# STEP 2: Display the shape, column names, and data types of each column.
#-----------------------------------------------------------------------
print(students.shape)
print(students.columns)
print(students.dtypes)
#-----------------------------------------------------------------------
# STEP 3: Run df.describe(), identify which columns are included in the output,
# and explain why certain columns are excluded.
#-----------------------------------------------------------------------
""""Describe() works on numerical columns only due to that only numerical columns are included in the output."""

students.describe()
#-----------------------------------------------------------------------
# STEP 4: Rename the column score to final_score and grade to letter_grade
# without modifying the original DataFrame (save the result to a new variable).
#-----------------------------------------------------------------------
students_renamed=students.rename(columns={"score":"final_score","grade":"letter_grade"})
students_renamed
##-----------------------------------------------------------------------
# STEP 5: From the renamed DataFrame, select only the name, final_score, and letter_grade columns and display the result.
#-----------------------------------------------------------------------

students_renamed[["name","final_score","letter_grade"]]

#-----------------------------------------------------------------------
# STEP 5: Using iloc, access the first 3 rows and all columns.
#Then using loc, access rows with index labels 1 and 3, and only the name and grade columns.
#-----------------------------------------------------------------------
students.iloc[0:3,]  # Exclusive the last value in a range

students.loc[1:3,['name','grade']] # Inclusive the last value in a range

      name  age  score grade
0    Alice   22   88.5     A
1      Bob   20   73.0     B
2  Charlie   21   91.0     A
3    Diana   23   65.5     C

In [7]:
#-----------------------------------------------------------------------
# STEP 2: Display the shape, column names, and data types of each column.
#-----------------------------------------------------------------------
print(students.shape)
print(students.columns)
print(students.dtypes)

(4, 4)

In [8]:
print(students.columns)

Index(['name', 'age', 'score', 'grade'], dtype='object')

In [9]:
print(students.dtypes)

name      object
age        int64
score    float64
grade     object
dtype: object

In [12]:

#-----------------------------------------------------------------------
# STEP 3: Run df.describe(), identify which columns are included in the output,
# and explain why certain columns are excluded.
#-----------------------------------------------------------------------
""""Describe() works on numerical columns only due to that only numerical columns are included in the output."""

students.describe()

             age      score
count   4.000000   4.000000
mean   21.500000  79.500000
std     1.290994  12.267844
min    20.000000  65.500000
25%    20.750000  71.125000
50%    21.500000  80.750000
75%    22.250000  89.125000
max    23.000000  91.000000

In [13]:
#-----------------------------------------------------------------------
# STEP 4: Rename the column score to final_score and grade to letter_grade
# without modifying the original DataFrame (save the result to a new variable).
#-----------------------------------------------------------------------
students_renamed=students.rename(columns={"score":"final_score","grade":"letter_grade"})
students_renamed
#

      name  age  final_score letter_grade
0    Alice   22         88.5            A
1      Bob   20         73.0            B
2  Charlie   21         91.0            A
3    Diana   23         65.5            C

In [15]:
#-----------------------------------------------------------------------
# STEP 5: From the renamed DataFrame, select only the name, final_score, and letter_grade columns and display the result.
#-----------------------------------------------------------------------

students_renamed[["name","final_score","letter_grade"]]

      name  final_score letter_grade
0    Alice         88.5            A
1      Bob         73.0            B
2  Charlie         91.0            A
3    Diana         65.5            C

In [18]:

#-----------------------------------------------------------------------
# STEP 5: Using iloc, access the first 3 rows and all columns.
#-----------------------------------------------------------------------
students.iloc[0:3,]

      name  age  score grade
0    Alice   22   88.5     A
1      Bob   20   73.0     B
2  Charlie   21   91.0     A

In [19]:

#------------------------------------------------------------------------------------------
#Then using loc, access rows with index labels 1 and 3, and only the name and grade columns.
#------------------------------------------------------------------------------------------
students.loc[1:3,['name','grade']]

      name grade
1      Bob     B
2  Charlie     A
3    Diana     C